name: Cypress Tests

on:
  workflow_dispatch:
    inputs:
      cli:
        description: Run by cypress command line
        default: yarn cypress run --env allure=true

jobs:
  cypress-electron-tests:
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node-18.16.1-chrome-114.0.5735.133-1-ff-114.0.2-edge-114.0.1823.51-1
      options: --user 1001
    strategy: 
      fail-fast: false
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17' # Escolha a versão do Java que você precisa instalar
      - name: Check Java version
        run: java -version
      - name: Get code
        uses: actions/checkout@v4.1.2
        
      - name: Install dependencies
        run: yarn install

      - name: Run E2E tests
        if: always()
        run: ${{ github.event.inputs.cli }}
            
      - name: Run generate report
        if: always()
        run: yarn allure generate ./allure-results/ -o ./report-server
        
      - name: Save Cypress report artifact
        if: always() 
        uses: actions/upload-artifact@v2
        with:
          name: cypress-report
          path: ./report-server/

      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: build/allure-results

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
